### ISSUE TITLE
Feature request: add image with nginx version 1.21

### ISSUE THREAD

**Issue by FrederickCoene** [dwchiang/nginx-php-fpm#6]
Hi,

First of all, thanks for sharing your docker images. This is really helpful!

I was wondering if you could create a new image with Nginx version 1.21.0?

There was an important security fix within nginx version 1.21.0:
Security: 1-byte memory overwrite might occur during DNS server
response processing if the "resolver" directive was used, allowing an
attacker who is able to forge UDP packets from the DNS server to
cause worker process crash or, potentially, arbitrary code execution
(CVE-2021-23017).

I would like to have the following alpine image:
8.0.8-fpm-1.21.1-nginx-alpine3.13

Thanks in advance.

**Comment by dwchiang** [comment]
Thank you for the feedback and heads-up :) 
I would love to add nginx version 1.21.0 in the following days.

**Comment by dwchiang** [comment]
Hi @FrederickCoene ,

I did some automation works on this project so that I can easier adding future Nginx version changes, but therefore I changed the docker image tag naming rule.

The nginx 1.21.1 docker image is based on alpine3.14, so the new tag which is close to your need is named `8.0.8-fpm-alpine3.14-nginx-1.21.1` now. Please kindly give it a try.

I am working on pushing all the modified Dockerfiles into project repo, but it may spend couple days to clean up :p Just in case you want to double check the Dockerfile source code.

**Comment by dwchiang** [comment]
Just finished all the testings across all the Dockerfiles with modified image tag naming rule, and pushed into git repo. I will close this issue for now :)
